name: Deployment

on:
  workflow_dispatch:
    inputs:
      network:
        description: The EVM compatible network.
        default: goerli
        required: true

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      ETHERSCAN_VERIFICATION: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn

      - name: Deploy
        run: |
          echo RPC_URL=${{ env.RPC_URL }} >> .env
          echo DEPLOYER_MNEMONIC=${{ env.DEPLOYER_MNEMONIC }} >> .env
          echo ETHERSCAN_KEY=${{ env.ETHERSCAN_KEY }} >> .env
          echo ETHERSCAN_VERIFICATION=${{ env.ETHERSCAN_VERIFICATION }} >> .env
          make deploy

      - name: Verification
        run: |
          echo ETHERSCAN_VERIFICATION=true >> .env
          make ETHERSCAN_VERIFICATION_CONTRACT=PoolConfigurator,PoolAddressesProvider,ACLManager verify
          make ETHERSCAN_VERIFICATION_CONTRACT=PoolCore,PoolMarketplace,PoolParameters verify
          make ETHERSCAN_VERIFICATION_CONTRACT=ProtocolDataProvider,UiPoolDataProvider,WalletBalanceProvider verify
          make ETHERSCAN_VERIFICATION_CONTRACT=WETHGatewayProxy,WPunkGatewayProxy,UniswapV3GatewayProxy verify
          make ETHERSCAN_VERIFICATION_CONTRACT=ParaSpaceOracle verify
          make ETHERSCAN_VERIFICATION_CONTRACT=Seaport,SeaportAdapter,Conduit verify

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.inputs.network }}-deployed-contracts-${{ github.sha }}
          path: deployed-contracts.json
