name: Etherscan Verification

on:
  workflow_dispatch:
    inputs:
      network:
        description: The EVM compatible network.
        default: goerli
        required: true
      ref:
        description: The verification branch, tag or SHA
        required: true
      verifyContract:
        description: The contract to be verified
        required: true

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      NETWORK: ${{ github.event.inputs.network }}
      REF: ${{ github.event.inputs.ref }}
      ETHERSCAN_VERIFICATION_CONTRACT: ${{ github.event.inputs.verifyContract }}
      ETHERSCAN_VERIFICATION: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true
          ref: ${{ env.REF }}

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn

      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: ${{ github.event.inputs.network }}-deployed-contracts-${{ github.event.inputs.ref }}
          path: ${{ github.event.inputs.network }}-deployed-contracts-${{ github.event.inputs.ref }}

      - name: Verification
        run: |
          cat ${{ github.event.inputs.network }}-deployed-contracts-${{ github.event.inputs.ref }} > deployed-contracts.json
          echo NETWORK=${{ env.NETWORK }} >> .env
          echo RPC_URL=${{ env.RPC_URL }} >> .env
          echo DEPLOYER_MNEMONIC=${{ env.DEPLOYER_MNEMONIC }} >> .env
          echo ETHERSCAN_KEY=${{ env.ETHERSCAN_KEY }} >> .env
          echo ETHERSCAN_VERIFICATION=${{ env.ETHERSCAN_VERIFICATION }} >> .env
          make ETHERSCAN_VERIFICATION_CONTRACT=${{ env.ETHERSCAN_VERIFICATION_CONTRACT }} verify
